### ISSUE TITLE
Document usage of ServiceAccount vs ServiceAccountAnnotations

### ISSUE THREAD

**Issue by isaaguilar** [GalleyBytes/terraform-operator#10]
Usage of `spec.serviceAccount` will negate use of `spec.credentials[].serviceAccountAnnotations` and it should be documented how or when to use each.

**Comment by jstrachan** [comment]
will do. The former reuses an existing service account; the latter adds extra annotations to the SA thats created for each Terraform resource. Any particular place you'd like the docs other than on the go structs?

**Comment by isaaguilar** [comment]
I would update `docs/provider-credentials.md` for now.

**Comment by asaintsever** [comment]
Maybe you also have to add `ServiceAccount` field in `deploy/crds/tf.isaaguilar.com_terraforms_crd.yaml` and also regenerate code using `make openapi-gen` (since `ServiceAccount` is missing from `zz_generated.openapi.go`)

**Comment by isaaguilar** [comment]
I'm also in the process of upgrading the operator-sdk to >=v1. By doing that, the apiVersion for `apiextensions.k8s.io` gets updated to v1 in the crd. I'll make a new release with the updated crd at that time.
