### ISSUE TITLE
Failed to pull image at init stage (v0.9.0)

### ISSUE THREAD

**Issue by ben-bud** [GalleyBytes/terraform-operator#115]
Throwing the following error: `Failed to pull image "ghcr.io/galleybytes/terraform-operator-tftaskv1:latest": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/galleybytes/terraform-operator-tftaskv1:latest": failed to resolve reference "ghcr.io/galleybytes/terraform-operator-tftaskv1:latest": ghcr.io/galleybytes/terraform-operator-tftaskv1:latest: not found`

Trying docker pull ghcr.io/galleybytes/terraform-operator-tftaskv1:latest returns: Error response from daemon: manifest unknown

Missing tag? https://github.com/isaaguilar/terraform-operator/blob/c5e61165398300d9d8efe972c752d64cb38b471c/pkg/apis/tf/v1alpha2/terraform_types.go#L15

**Comment by isaaguilar** [comment]
It's not missing, it's not the decision of tfo to decide on the version of terraform to use. This was allowed before v0.9.x, but I thought it was a bad design to pick a version for the user. I can make a latest, but if latest bumps a minor version, who is responsible for ensuring the module is compatible?

**Comment by ben-bud** [comment]
Thanks for the reply. I think making a latest tag would be useful for those like me who try to use the terraform operator without specifying, however it does make sense to force the user to specify it with terraformVersion.
