### ISSUE TITLE
add a 'tf' CRD shortName?

### ISSUE THREAD

**Issue by jstrachan** [GalleyBytes/terraform-operator#13]
quite a lot of CRDs have nice short names. e.g.

*  `PipelineRun` => `pr` 
* `Service` => `svc` 
* `ReplicaSet` => `rs`

it might be nice to add a `tf` short name for the `Terraform` resource so that you can type:

```bash
kubectl get tf
```

Though I confess I'm not 100% sure how to add to the `shortNames:` in the generated CRD resource yet via the `operator-sdk`. Maybe we try figure this one out after the move to the latest greatest `operator-sdk`?

**Comment by isaaguilar** [comment]
I was just about to open an issue for this exact item. You beat me to the punch.

**Comment by isaaguilar** [comment]
Good news, terraform-operator is now built on operator-sdk v1.4.0 as of https://github.com/isaaguilar/terraform-operator/pull/16
