### ISSUE TITLE
Global variable docs

### ISSUE THREAD

**Issue by davhdavh** [GalleyBytes/terraform-operator#145]
http://tf.galleybytes.com/docs/features/globalenvs/

shows how to set it for a `kubectl` installation.

It really should show how to do it for the helm install process, since that is the recommended install.

I would make a PR for it, but I cannot find the location of the doc repo?

**Comment by isaaguilar** [comment]
https://github.com/isaaguilar/terraform-operator-website/blob/master/content/docs/features/globalenvs.md

I'm on a really old version of `hugo` , but if it hasn't changed that much, running `hugo server` from the root fo the docs repo should open up a localhost to see your changes. 

my hugo version for reference:

```bash
hugo version
hugo v0.88.1+extended darwin/amd64 BuildDate=unknown
```
