### ISSUE TITLE
Please add terraform-operator:v0.11.0 to ghcr

### ISSUE THREAD

**Issue by mihaigalos** [GalleyBytes/terraform-operator#159]
The `terraform-operator:v0.11.0` was previously hosted on Docker Hub. It is now hosted on GitHub container registry.

We are working on an automatic image updater for kustomize which will also patch the tag.

We've manually updated the url to point to ghcr, but since we're using `v0.11.0` of the operator, it's now being pulled from ghcr and that tag is not present.

Can you please push it there as well?

The criterion for success is the following command's success:
```
docker pull ghcr.io/galleybytes/terraform-operator:v0.11.0
```

**Comment by isaaguilar** [comment]
Added https://github.com/GalleyBytes/terraform-operator/pkgs/container/terraform-operator/131001490?tag=v0.11.0
