### ISSUE TITLE
Typo in new CRD status property name

### ISSUE THREAD

**Issue by smasset-orange** [GalleyBytes/terraform-operator#166]
New property `retryEventReson` should probably be renamed to `retryEventReason`

https://github.com/GalleyBytes/terraform-operator/blob/1a5d46a6de7a85481466f7408bf3bc5a4d0091c3/deploy/crds/tf.galleybytes.com_terraforms_crd.yaml#L2567

**Comment by isaaguilar** [comment]
Oh gosh 😢  I'll fix it.

**Comment by isaaguilar** [comment]
Fixed in https://github.com/GalleyBytes/terraform-operator/commit/0e509b4e49ec327a0cd40a7753e57098b355a55e#diff-8151fb5e285384b4df8c7222e8f4cd14aefd448c5fce697ec2122d226cf21a70
