### ISSUE TITLE
create a new helm chart for 0.3.4?

### ISSUE THREAD

**Issue by jstrachan** [GalleyBytes/terraform-operator#18]
I'd raise a PR if I knew how the previous charts have have been created ;)

**Comment by jstrachan** [comment]
btw here's a github action I've used in the past to automate releasing charts:
https://github.com/cdfoundation/tekton-helm-chart/blob/master/.github/workflows/publish.yml

**Comment by jstrachan** [comment]
here's a PR https://github.com/isaaguilar/helm-charts/pull/2

**Comment by isaaguilar** [comment]
merged
