### ISSUE TITLE
Suggestion: (auto)generate clientset from spec

### ISSUE THREAD

**Issue by milosgajdos** [GalleyBytes/terraform-operator#24]
This will make it easy to create `tf CRD`s programmatically from other `Go` programs by importing the autogenerated clientset into them as a dependency.

**Comment by isaaguilar** [comment]
That would be something like this, right?  https://github.com/isaaguilar/terraform-operator/blob/26a57ef2ea9253065fbe72765f782e687d9d1144/pkg/apis/tf/v1alpha1/terraforms.go

**Comment by milosgajdos** [comment]
Yes, that will do.

I believe you should be able to generate it from source with some struct tags using [k8s-codegen](https://github.com/kubernetes/code-generator), so you don't have to deal with any code yourself.

There is a nice example about how to do it in the [sample-controller repo](https://github.com/kubernetes/sample-controller/blob/master/hack/update-codegen.sh). I have done this in past many times for the controllers I've written.

But as I said the code in the link you pasted will do just fine 👍
