### ISSUE TITLE
Update ImagePullPolicy for terraform execution jobs

### ISSUE THREAD

**Issue by mbaumims** [GalleyBytes/terraform-operator#30]
We have been using [kind](https://kind.sigs.k8s.io/) as part of our testing suite for our project. Kind allows you to pre-load docker images so that it does not need to reach out to Docker Hub, AWS ECR or where ever to pull an image. Since we've created our own custom docker image that is used as the terraform execution image for the jobs created by the operator we hit a snag. We have been unable to use this workflow since the `ImagePullPolicy` is set to `Always` for the jobs that the terraform operator creates. The consequence is that the job fails to start since kind does not have the credentials to reach out to the AWS ECR (where we store our images). I have tested and know that it works if the `ImagePullPolicy` is set to `IfNotPresent`. In fact I modified the controller and built a new image to unblock us. So I'm checking if we could update the `ImagePullPolicy` to `IfNotPresent`. I can offer a PR if you wish.

**Comment by asaintsever** [comment]
Hello,

May I suggest you add this possibility in the CRD instead of having this pull policy hardcoded in the controller? 

This way, anyone can set the pull policy in the Terraform resource. Having `Always` as the default value makes sense from a security standpoint (this is the recommended behavior to make sure the local image has not been tampered or replaced by a malicious user/process).

**Comment by mbaumims** [comment]
@asaintsever Good point, that is a sane suggestion. I can re-work my changes to update the CRD. This will impact the helm chart as well, I believe. I'm not sure what the workflow would be to update these two in tandem.

**Comment by asaintsever** [comment]
This repo only deals with the controller's code + some manifests (including CRD under `deploy/crds` folder) to quickly install the operator for testing purpose. As for the Helm chart, it is located in a distinct repo: https://github.com/isaaguilar/helm-charts/tree/master/charts/terraform-operator

So you'll have to submit 2 PRs (and to copy the CRD as it belongs to both repos).

**Comment by mbaumims** [comment]
@asaintsever Okay, that's what I expected. I'll wait to hear back from @isaaguilar and then prepare the PRs.

**Comment by mbaumims** [comment]
@asaintsever It dawned on me yesterday that I think the appropriate solution would be to add a variable to the helm chart for the operator to configure the `ImagePullPolicy`, rather than in the Terraform CRD. I say this since I'm not sure that I want to configure this individually for one resource to another. If there is a real use case for this, I'd still like to be able to set a default `ImagePullPolicy` for all jobs and only override it in the CRD if necessary.

**Comment by asaintsever** [comment]
For sure this is doable even if I am fine with the `Always` value currently enforced by the controller. If someone happens to need this value changed in some exceptional occasions, then having to do so via the CRD seems a minor hassle to me as, for production usage it is expected you shift back to `Always` to follow best security guidelines. If you publish your Terraform custom image in a private registry (ie credentials are required), maybe what is lacking here is the possibility, in the CRD, to provide a reference to a k8s secret to set the `imagePullSecrets` field in the terraform job manifest. The `Always` pull policy would not be an issue to you anymore then. 

My two cents, feel free to propose your PR of course :-)

**Comment by isaaguilar** [comment]
I wouldn't be opposed to adding a spec item for the terraform-runner pull policy, I think the default should be "Always" unless its defined. So something like like 

```yaml
# ...
kind: Terraform
spec:
  terraformRunnerPullPolicy: IfNotPresent  # defaults to Always
  # ...
```

Let me know if you want to give that a shot @mbaumims, or I'm willing to make that change.

**Comment by mbaumims** [comment]
@isaaguilar Thanks for taking care of this. I had meant to follow up with a PR, but I got a little bit busy.
