### ISSUE TITLE
Execute changes starting from terraform 0.15.X

### ISSUE THREAD

**Issue by den-saw** [GalleyBytes/terraform-operator#43]
https://github.com/isaaguilar/terraform-operator/blob/master/docker/terraform/run.sh#L19

```
terraform init .
```
should be replaced with
```terraform init```

to let script work with terraform 0.15.X+
so the new image should be rebuilded.

**Comment by isaaguilar** [comment]
Thanks for adding this issue. New builds for the terraform runners that are >= 0.15.x are coming soon.

**Comment by isaaguilar** [comment]
Images are up. Thanks for opening up this issue.
