### ISSUE TITLE
support specifying the serviceAccount on a Terraform

### ISSUE THREAD

**Issue by jstrachan** [GalleyBytes/terraform-operator#6]
[Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) on Google Cloud is a great way to associate a k8s ServiceAccount with a GCP Service Account + Cloud IAM Roles. Its currently a little fiddly though; you need to link the k8s SA name + namespace with the GCP project + identity.

Its often easier to do this once and then reuse the ServiceAccount - rather than dynamically creating a new k8s SA for each `Terraform` resource.

so lets allow users to specify an exact k8s ServiceAccount to be used in a `Terraform`

**Comment by isaaguilar** [comment]
This is a great idea. Aws has a similar concept with iam-roles for service accounts (IRSA) and requires ServiceAccount annotations. Currently IRSA is a hardcoded in terraform-operator's "credentials" for ease of use. Adding a generic annotations is by far more powerful and much more configurable.
