### ISSUE TITLE
Add label to runner pod

### ISSUE THREAD

**Issue by Sbou** [GalleyBytes/terraform-operator#86]
Hi,

I want to use this TF operator in a Azure AKS cluster.
To be able to create Azure ressources, Iwould like to use an Azure Managed Identity bind to the runner pod with the "Azure Pod Identity" feature.
Unforunately, to do that I need to add a label to the pod "runner".

Is it possible to define additionnal labels with the helm chart or TFO resource?

Thank you,

**Comment by isaaguilar** [comment]
I can add it to the next release.  I'll try to get that out soon.

**Comment by Sbou** [comment]
Wow!!!

Super fast :) 
Thank you
