### ISSUE TITLE
which version of the operator-sdk is being used? 

### ISSUE THREAD

**Issue by jstrachan** [GalleyBytes/terraform-operator#9]
the docs imply [0.15.1](https://github.com/isaaguilar/terraform-operator/blob/master/README.md#development) which doesn't exist yet at https://github.com/operator-framework/operator-sdk/releases/tag/v1.4.0 or is it a different `operator-sdk` binary from somewhere else?

with 1.4.0 there's no `operator-sdk generate k8s` or `operator-sdk generate crds`

**Comment by asaintsever** [comment]
Hi @jstrachan 
It does exist: https://github.com/operator-framework/operator-sdk/releases/tag/v0.15.1 (version in use in go.mod https://github.com/isaaguilar/terraform-operator/blob/master/go.mod#L38)

**Comment by isaaguilar** [comment]
I've currently started the upgrade process to get to >= 1.0.0.  I've got a branch started https://github.com/isaaguilar/terraform-operator/tree/operator-sdk-upgrade that is on version 0.19.4. There's a bunch of little breaking changes to get to 1.0.0 which I was going to look into in the next few days here.

**Comment by jstrachan** [comment]
@asaintsever aha thanks!!! doh - I totally totally misread the decimal points in 1.4.0 versus 0.15.1 and got confused! :)
