### ISSUE TITLE
Keep latest pods

### ISSUE THREAD

**Issue by flanaras** [GalleyBytes/terraform-operator#94]
Hi, would it make sense to have a flag, i.e. `keepLatestPods`, in the CRD similar to [`keepCompletedPods`](https://github.com/isaaguilar/terraform-operator/blob/95d942c1842add7c3e9da94294220585dbf69631/deploy/crds/tf.isaaguilar.com_terraforms_crd.yaml#L259) that clears up pods (setup, init, plan, apply) from previous executions, only keeping pods from the last/current execution?

Such a feature would help us track and visualise the status and timestamp of terraform's last execution in a dashboard like the one in ArgoCD, without having to dig into logs.

As far I have search this is not currently possible, am I missing something obvious?

**Comment by isaaguilar** [comment]
I like the idea for `keepLatestPods`. I'll add this in the next release. 

As far as logs go, this has been on my mind and I finally started a [CLI for tfo](https://github.com/isaaguilar/terraform-operator-cli) that will be able to intelligently gather data from a generation.  The cli is still rough around the edges, but I was going to be adding 

```bash
tfo logs <tfo-resource>
```

and

```bash
tfo logs <tfo-k8s-resource> --generation <n>
```

This command would show the init, plan, and apply (or how ever many were completed).  Before I can do this, I need to write logs somewhere where they will persist and can be organized.

**Comment by flanaras** [comment]
Thanks, that will be very much appreciated.

Nice to know about the cli, I was not aware about that.

**Comment by isaaguilar** [comment]
Release v0.8.0 with this change. See https://github.com/isaaguilar/terraform-operator/releases/tag/v0.8.0

**Comment by flanaras** [comment]
I tested it out, works as expected!
