### ISSUE TITLE
How to use the output secret?

### ISSUE THREAD

**Issue by Sbou** [GalleyBytes/terraform-operator#96]
Hi,

I would like to reference a value generated by my terraform as output secret.
My problem is about the value stored by the operator.
I expected to have only the value but I received the Terraform JSON structure.

What is the best practise to reference this value in a environment variable in a `Deployment`?

Thank you

**Comment by isaaguilar** [comment]
Oh you're right, the output shouldn't be the JSON structure and it should just be the value. Will need look at updating the behavior of outputs soon.
